import movingBar from "./module/movingBar";
import pageNavigation from "./module/pageNavigation";
import canUseWebp from "./module/canUseWebp";
import smoothScroll from "./module/smoothScroll";
import searchForm from "./module/searchForm";
import searchMatches from "./module/searchMatches";
import previewSlider from "./module/previewSlider";
import hidePreviewSlides from "./module/showPreviewSlides";
import modifiedCarsSlider from "./module/modifiedCarsSlider";
import showBlocks from "./module/showBlocks";
import mobileMenu from "./module/mobileMenu";
import showYears from "./module/showYears";
import accordion from "./module/accordion";
import filter from "./module/filter";
import siteSelect from "./module/siteSelect";
import footerLinks from "./module/footerLinks";
import customSelect from "./module/customSelect";
import hideText from "./module/hideText";
// import select2 from "./module/select2"

svg4everybody({});
pageNavigation();
canUseWebp();
smoothScroll();
movingBar();
searchForm();
searchMatches();
previewSlider();
hidePreviewSlides();
modifiedCarsSlider();
showBlocks();
mobileMenu();
showYears();
accordion();
filter();
siteSelect();
footerLinks();
customSelect();
hideText();
// select2();